"""Drift gate: committed config artifacts must match the generator, and every
hand-authored config (docker + presets) must parse against the ``Config`` schema.
"""

from __future__ import annotations

import glob
import importlib.util
import json
import types
from pathlib import Path
from typing import Any

import pytest
import yaml

from sf2loki import configdoc
from sf2loki.config import Config, _interpolate_env

ROOT = Path(__file__).resolve().parents[1]


def _load_script(name: str) -> types.ModuleType:
    """Import a deploy/grafana/*.py generator script as a standalone module.

    These scripts aren't part of the ``sf2loki`` package (no ``__init__.py`` in
    ``deploy/grafana``), and only write their output file under ``if __name__ ==
    '__main__'`` — importing them just builds the in-memory dict, with no disk
    I/O, so this is safe to do from a test.
    """
    path = ROOT / "deploy" / "grafana" / f"{name}.py"
    spec = importlib.util.spec_from_file_location(f"_drift_check_{name}", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_dashboard_json_matches_generator():
    module = _load_script("gen_dashboard")
    expected = json.dumps(module.dashboard, indent=2) + "\n"
    assert (ROOT / "deploy/grafana/sf2loki-dashboard.json").read_text() == expected


def test_alerts_yaml_matches_generator(monkeypatch: pytest.MonkeyPatch):
    # The committed alerts.yaml is generated with the default (unset) datasource
    # UID override — make sure a stray env var in the test environment can't
    # produce a false drift failure.
    monkeypatch.delenv("SF2LOKI_PROMETHEUS_DS_UID", raising=False)
    module = _load_script("gen_alerts")
    header = (
        "# Generated by deploy/grafana/gen_alerts.py — do not hand-edit.\n"
        "# Regenerate with: python3 deploy/grafana/gen_alerts.py (or `just gen-grafana`).\n"
    )
    expected = header + yaml.dump(
        module.manifest, sort_keys=False, default_flow_style=False, width=100
    )
    assert (ROOT / "deploy/grafana/alerts.yaml").read_text() == expected


def test_example_yaml_matches_generator():
    assert (ROOT / "config.example.yaml").read_text() == configdoc.example_yaml()


def test_reference_md_matches_generator():
    assert (ROOT / "docs/config-reference.md").read_text() == configdoc.reference_markdown()


def _known_keys(model: type[Any]) -> set[str]:
    return set(model.model_fields)


def _assert_known_keys(data: dict[str, Any], model: type[Any], where: str) -> None:
    """Assert every key in ``data`` is a known field of ``model`` (recursing one
    level into nested mapping/list-of-mapping fields so a misspelled nested key
    is also caught).
    """
    known = _known_keys(model)
    unknown = set(data) - known
    assert not unknown, f"{where}: unknown key(s) {sorted(unknown)} (known: {sorted(known)})"
    for name, value in data.items():
        field = model.model_fields[name]
        annotation = configdoc._unwrap_optional(field.annotation)
        if configdoc._is_model_type(field.annotation) and isinstance(value, dict):
            _assert_known_keys(value, annotation, f"{where}.{name}")
        item_model = configdoc._list_item_model_type(field.annotation)
        if item_model is not None and isinstance(value, list):
            for i, item in enumerate(value):
                if isinstance(item, dict):
                    _assert_known_keys(item, item_model, f"{where}.{name}[{i}]")


@pytest.mark.parametrize(
    "path",
    sorted(map(Path, glob.glob(str(ROOT / "examples/presets/*.yaml")))),
)
def test_preset_configs_have_known_keys(path: Path):
    # Presets are fragments (not a full Config), so validate structurally:
    # every top-level and nested key must be a known field on the schema.
    data = yaml.safe_load(path.read_text())
    assert isinstance(data, dict)
    _assert_known_keys(data, Config, path.name)


def test_docker_config_constructs_against_schema(monkeypatch: pytest.MonkeyPatch):
    # config.docker.yaml is a full config (references ${VAR}s + *_file secrets).
    # Stub the env vars it interpolates and construct a real Config, but skip
    # resolve_secrets() so the (non-existent, in CI) mounted secret files don't
    # need to exist.
    env = {
        "SF_LOGIN_URL": "https://example-dev-ed.my.salesforce.com",
        "SF_CLIENT_ID": "3MVG9test-client-id",
        "SF_USERNAME": "svc@example.com",
        "GC_LOKI": "https://logs-prod-999.grafana.net/loki/api/v1/push",
        "GC_LOKI_USER": "123456",
        "GC_OTLP_ENDPOINT": "https://otlp-gateway-prod-999.grafana.net/otlp",
        "GC_OTLP_USER": "654321",
    }
    for key, value in env.items():
        monkeypatch.setenv(key, value)

    raw = yaml.safe_load((ROOT / "config.docker.yaml").read_text())
    assert isinstance(raw, dict)
    _assert_known_keys(raw, Config, "config.docker.yaml")

    data = _interpolate_env(raw)
    cfg = Config(**data)  # deliberately not resolve_secrets(cfg) — no secret files here.

    assert cfg.salesforce.login_url == env["SF_LOGIN_URL"]
    assert cfg.sink.loki.url == env["GC_LOKI"]
