# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loki_push.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'loki_push.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0floki_push.proto\x12\x08logproto\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n\x0bPushRequest\x12(\n\x07streams\x18\x01 \x03(\x0b\x32\x17.logproto.StreamAdapter\"V\n\rStreamAdapter\x12\x0e\n\x06labels\x18\x01 \x01(\t\x12\'\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x16.logproto.EntryAdapter\x12\x0c\n\x04hash\x18\x03 \x01(\x04\"\x83\x01\n\x0c\x45ntryAdapter\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04line\x18\x02 \x01(\t\x12\x36\n\x12structuredMetadata\x18\x03 \x03(\x0b\x32\x1a.logproto.LabelPairAdapter\"/\n\x10LabelPairAdapter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loki_push_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUSHREQUEST']._serialized_start=62
  _globals['_PUSHREQUEST']._serialized_end=117
  _globals['_STREAMADAPTER']._serialized_start=119
  _globals['_STREAMADAPTER']._serialized_end=205
  _globals['_ENTRYADAPTER']._serialized_start=208
  _globals['_ENTRYADAPTER']._serialized_end=339
  _globals['_LABELPAIRADAPTER']._serialized_start=341
  _globals['_LABELPAIRADAPTER']._serialized_end=388
# @@protoc_insertion_point(module_scope)
