#!/usr/bin/env python3
"""Synthetic Salesforce activity generator — makes a dev org look busy and real.

Drives constant, low-level, randomised activity through the Salesforce REST API
so that EventLogFile (ELF) ingestion and the streaming pipeline have realistic
data to chew on. Covers the breadth of event categories an org normally sees:

  * object CRUD (Account, Contact, Lead, Opportunity, Case, Task, Event)
    -> API / RestApi ELF events, and the underlying records product queries hit
  * SOQL queries                       -> API ELF events
  * SOSL searches                      -> Search ELF events
  * Bulk API 2.0 ingest + query jobs   -> BulkApi ELF events
  * composite / batch requests         -> API ELF events
  * sObject + global describe          -> API (metadata) ELF events
  * file upload + download             -> ContentTransfer / file ELF events
  * anonymous Apex (Tooling API)       -> ApexExecution ELF events
  * periodic re-auth + token revoke    -> Login / Logout events + LoginEventStream

Capability-gated (offered only when discover() finds them enabled in the org):
  * report runs, sync + async          -> Report / AsyncReportRun ELF events
  * dashboard reads                    -> Dashboard ELF events
  * Campaign / CampaignMember, Contract -> more object coverage

It authenticates with the same JWT-bearer credentials sf2loki uses (read from a
`.env` file or the environment), stamps every record it creates with a marker in
the Description field, and can clean them all up again with `--cleanup`.

Cannot be generated via API (documented limitation): URI / LightningPageView /
LightningInteraction ELF types require a real browser UI session.

Usage
-----
  # continuous low-level noise (~6 ops/min) until Ctrl-C:
  python scripts/generate_activity.py --env-file .env.dev

  # heavier burst for an hour:
  python scripts/generate_activity.py --env-file .env.dev --ops-per-min 30 --duration 3600

  # delete everything this tool ever created:
  python scripts/generate_activity.py --env-file .env.dev --cleanup

This is a dev/test utility. It only ever touches the org named by SF_LOGIN_URL.
"""

from __future__ import annotations

import argparse
import asyncio
import base64
import contextlib
import logging
import os
import random
import re
import signal
import string
import sys
import unicodedata
import urllib.parse
from collections import defaultdict, deque
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path

import httpx
import jwt

log = logging.getLogger("gen_activity")

# Marker stamped into every created record's Description so --cleanup can find
# them. Chosen to be obvious in the UI and unlikely to collide with real data.
MARKER = "[sf2loki-synthetic]"

# Realistic data pools live alongside the script; generated by the doc'd fleet.
DATA_DIR = Path(__file__).resolve().parent / "data"

# JWT assertion lifetime — Salesforce rejects exp > 3 minutes out.
_JWT_LIFETIME = timedelta(seconds=180)

# ---------------------------------------------------------------------------
# Realistic-ish data pools
# ---------------------------------------------------------------------------

_FIRST_NAMES = [
    "Olivia", "Liam", "Emma", "Noah", "Ava", "Ethan", "Sophia", "Mason",
    "Isabella", "Lucas", "Mia", "Oliver", "Amelia", "Elijah", "Harper",
    "James", "Evelyn", "Benjamin", "Abigail", "Henry", "Priya", "Aarav",
    "Wei", "Fatima", "Diego", "Yuki", "Kwame", "Ingrid", "Mateo", "Aisha",
]
_LAST_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller",
    "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez",
    "Wilson", "Anderson", "Nguyen", "Patel", "Kim", "Okafor", "Rossi",
    "Andersson", "Tanaka", "Muller", "Silva", "Haddad", "Novak", "Petrov",
]
_COMPANY_BASES = [
    "Northwind", "Contoso", "Acme", "Globex", "Initech", "Umbra", "Vertex",
    "Cascade", "Ironclad", "Meridian", "Kestrel", "Solstice", "Aurora",
    "Redwood", "Sterling", "Beacon", "Cobalt", "Everest", "Harbor", "Lattice",
    "Nimbus", "Pinnacle", "Quantum", "Riverstone", "Summit", "Tideline",
]
_COMPANY_QUALIFIERS = [
    "Analytics", "Logistics", "Systems", "Labs", "Digital", "Robotics",
    "Biotech", "Capital", "Foods", "Energy", "Health", "Media", "Retail",
    "Software", "Manufacturing", "Consulting", "Freight", "Networks",
]
_COMPANY_SUFFIXES = ["Inc", "LLC", "Corp", "Group", "Holdings", "Co", "Partners", "GmbH"]
_INDUSTRIES = [
    "Agriculture", "Banking", "Biotechnology", "Chemicals", "Communications",
    "Construction", "Consulting", "Education", "Electronics", "Energy",
    "Engineering", "Entertainment", "Finance", "Healthcare", "Hospitality",
    "Insurance", "Manufacturing", "Media", "Retail", "Technology",
    "Telecommunications", "Transportation", "Utilities",
]
_RATINGS = ["Hot", "Warm", "Cold"]
_ACCOUNT_TYPES = [
    "Prospect", "Customer - Direct", "Customer - Channel",
    "Channel Partner / Reseller", "Technology Partner", "Other",
]
_LEAD_STATUSES = ["Open - Not Contacted", "Working - Contacted"]
_LEAD_SOURCES = ["Web", "Phone Inquiry", "Partner Referral", "Purchased List", "Other"]
_OPP_STAGES = [
    "Prospecting", "Qualification", "Needs Analysis", "Value Proposition",
    "Id. Decision Makers", "Proposal/Price Quote", "Negotiation/Review",
]
_OPP_STAGE_ADVANCE = [*_OPP_STAGES, "Closed Won", "Closed Lost"]
_CASE_STATUSES = ["New", "Working", "Escalated"]
_CASE_ORIGINS = ["Phone", "Email", "Web"]
_CASE_PRIORITIES = ["High", "Medium", "Low"]
_CASE_TYPES = ["Question", "Problem", "Feature Request"]
# (city, country) using full-name country integration values so they validate
# whether or not the org has State & Country picklists enabled. State is
# deliberately omitted — its valid set is country-dependent and picklist-fussy.
_CITIES = [
    ("San Francisco", "United States"), ("Austin", "United States"),
    ("New York", "United States"), ("London", "United Kingdom"),
    ("Berlin", "Germany"), ("Toronto", "Canada"),
    ("Sydney", "Australia"), ("Singapore", "Singapore"),
    ("Dublin", "Ireland"), ("Bengaluru", "India"),
]
_TITLES = [
    "VP Engineering", "Director of Operations", "Account Executive",
    "Procurement Manager", "CTO", "Head of Marketing", "IT Administrator",
    "Product Manager", "Finance Lead", "Customer Success Manager",
]
_TASK_SUBJECTS = [
    "Follow up", "Send quote", "Schedule demo", "Call back", "Email proposal",
    "Prepare contract", "Check in", "Renewal discussion", "Onboarding call",
]
_EVENT_SUBJECTS = [
    "Discovery call", "Product demo", "Quarterly review", "Kickoff meeting",
    "Contract review", "Solution workshop", "Executive briefing",
]
_CAMPAIGN_NAMES = [
    "Q3 Product Launch", "Summer Webinar Series", "Annual User Conference",
    "Partner Enablement Push", "Renewal Outreach", "Cloud Migration Program",
    "Year-End Promotion", "Analyst Briefing Tour", "Field Marketing Roadshow",
    "Customer Advocacy Program",
]
# Values from the standard Campaign Type / Status picklists.
_CAMPAIGN_TYPES = [
    "Conference", "Webinar", "Trade Show", "Public Relations", "Partners",
    "Referral Program", "Advertisement", "Email", "Telemarketing", "Other",
]
_CAMPAIGN_STATUSES = ["Planned", "In Progress", "Completed"]
# A handful of real, well-known companies for extra realism (dedup is handled by
# random suffixes + the duplicate-rule override). Industry values are picklist-valid.
_REAL_COMPANIES = [
    ("Microsoft", "Technology", "https://microsoft.com"),
    ("Salesforce", "Technology", "https://salesforce.com"),
    ("Amazon", "Retail", "https://amazon.com"),
    ("JPMorgan Chase", "Banking", "https://jpmorganchase.com"),
    ("Pfizer", "Biotechnology", "https://pfizer.com"),
    ("Toyota", "Manufacturing", "https://toyota.com"),
    ("Shell", "Energy", "https://shell.com"),
    ("Unilever", "Retail", "https://unilever.com"),
    ("Siemens", "Engineering", "https://siemens.com"),
    ("HSBC", "Banking", "https://hsbc.com"),
    ("Nestle", "Retail", "https://nestle.com"),
    ("Verizon", "Telecommunications", "https://verizon.com"),
    ("Boeing", "Manufacturing", "https://boeing.com"),
    ("AstraZeneca", "Biotechnology", "https://astrazeneca.com"),
    ("Accenture", "Consulting", "https://accenture.com"),
    ("Maersk", "Transportation", "https://maersk.com"),
    ("Vodafone", "Telecommunications", "https://vodafone.com"),
    ("Allianz", "Insurance", "https://allianz.com"),
    ("BASF", "Chemicals", "https://basf.com"),
    ("Marriott", "Hospitality", "https://marriott.com"),
]


@dataclass(frozen=True, slots=True)
class Company:
    name: str
    industry: str
    website: str
    description: str


@dataclass(frozen=True, slots=True)
class Person:
    first: str
    last: str
    title: str


# Small built-in fallback pools so the script still runs (and tests pass) when
# the data/*.csv files are absent. The CSVs, when present, dwarf these.
_FALLBACK_COMPANIES = [
    Company(f"{b} {q}", "Technology", f"https://{b.lower()}.example.com", f"{b} {q} services")
    for b, q in zip(_COMPANY_BASES[:12], _COMPANY_QUALIFIERS[:12], strict=False)
]
_FALLBACK_PEOPLE = [
    Person(f, ln, t)
    for f, ln, t in zip(_FIRST_NAMES, _LAST_NAMES, _TITLES * 3, strict=False)
]


def _read_csv_rows(path: Path, ncols: int) -> list[list[str]]:
    """Parse simple comma-separated rows, skipping blanks, comments, malformed."""
    rows: list[list[str]] = []
    if not path.exists():
        return rows
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split(",")]
        if len(parts) != ncols or any(not p for p in parts):
            continue
        rows.append(parts)
    return rows


def load_companies(data_dir: Path = DATA_DIR) -> list[Company]:
    rows = _read_csv_rows(data_dir / "companies.csv", 4)
    pool = [Company(n, i, w, d) for n, i, w, d in rows]
    return pool or list(_FALLBACK_COMPANIES)


def real_companies() -> list[Company]:
    """A few real, well-known companies mixed in for realism (dedup handled by
    random suffixes + the duplicate-rule override)."""
    return [
        Company(n, i, w, f"{n} - industry leader in {i.lower()}")
        for n, i, w in _REAL_COMPANIES
    ]


def load_people(data_dir: Path = DATA_DIR) -> list[Person]:
    rows = _read_csv_rows(data_dir / "people.csv", 3)
    pool = [Person(f, ln, t) for f, ln, t in rows]
    return pool or list(_FALLBACK_PEOPLE)


def marker_ids(records: list[dict], id_field: str = "Id") -> list[str]:
    """Ids of records whose Description carries the synthetic MARKER.

    Description is a Long Text Area and cannot be SOQL-filtered, so callers
    SELECT it and filter here client-side. *id_field* lets callers project a
    different id (e.g. ContentDocumentId when cleaning up files).
    """
    return [r[id_field] for r in records if MARKER in (r.get("Description") or "")]


def _uniqueify(name: str) -> str:
    """Append a short realistic-ish token often, so repeat runs rarely collide."""
    r = random.random()
    if r < 0.45:
        return name
    if r < 0.78:
        return f"{name} {random.randint(2, 999)}"
    return f"{name} {''.join(random.choices(string.ascii_uppercase, k=3))}"


def _ascii_local(s: str) -> str:
    """Fold accents and drop non-ASCII so the email local-part validates."""
    folded = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]", "", folded.lower()) or "user"


def _rand_email(first: str, last: str) -> str:
    domain = random.choice(["example.com", "mailinator.com", "test.dev", "acme-demo.co"])
    sep = random.choice([".", "_", ""])
    # 2-4 digit tag keeps addresses unique across the finite name pool.
    tag = "".join(random.choices(string.digits, k=random.randint(2, 4)))
    return f"{_ascii_local(first)}{sep}{_ascii_local(last)}{tag}@{domain}"


def _rand_phone() -> str:
    return f"+1 {random.randint(200, 989)}-{random.randint(200, 989)}-{random.randint(1000, 9999)}"


def _today() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%d")


def _future_date(max_days: int = 120) -> str:
    return (datetime.now(UTC) + timedelta(days=random.randint(1, max_days))).strftime("%Y-%m-%d")


def _soon_datetime() -> str:
    dt = datetime.now(UTC) + timedelta(hours=random.randint(1, 240))
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _desc(kind: str) -> str:
    return f"{MARKER} synthetic {kind} generated for observability testing."


# ---------------------------------------------------------------------------
# Config / env
# ---------------------------------------------------------------------------


def load_env_file(path: Path) -> None:
    """Load simple KEY=VALUE lines from *path* into os.environ (no overwrite)."""
    if not path.exists():
        raise SystemExit(f"env file not found: {path}")
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def _require(name: str) -> str:
    val = os.environ.get(name)
    if not val:
        raise SystemExit(f"missing required env var: {name}")
    return val


# ---------------------------------------------------------------------------
# Salesforce REST client
# ---------------------------------------------------------------------------


class Salesforce:
    """Thin async Salesforce REST wrapper with JWT-bearer auth + 401 refresh."""

    def __init__(self, client: httpx.AsyncClient, api_version: str) -> None:
        self._client = client
        self.api_version = api_version
        self.login_url = _require("SF_LOGIN_URL").rstrip("/")
        self.client_id = _require("SF_CLIENT_ID")
        self.username = _require("SF_USERNAME")
        key_path = Path(_require("SF_PRIVATE_KEY_FILE"))
        self._private_key = key_path.read_text()
        self.instance_url: str = ""
        self._token: str = ""
        self.login_count = 0
        self.logout_count = 0

    @property
    def _base(self) -> str:
        return f"{self.instance_url}/services/data/v{self.api_version}"

    def _mint_jwt(self) -> str:
        payload = {
            "iss": self.client_id,
            "sub": self.username,
            "aud": self.login_url,
            "exp": datetime.now(UTC) + _JWT_LIFETIME,
        }
        return jwt.encode(payload, self._private_key, algorithm="RS256")

    async def login(self) -> None:
        """(Re-)authenticate. Each call produces a fresh Login event + stream."""
        resp = await self._client.post(
            f"{self.login_url}/services/oauth2/token",
            data={
                "grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer",
                "assertion": self._mint_jwt(),
            },
        )
        if not resp.is_success:
            raise SystemExit(f"auth failed HTTP {resp.status_code}: {resp.text}")
        body = resp.json()
        self._token = body["access_token"]
        self.instance_url = body["instance_url"].rstrip("/")
        self.login_count += 1
        log.info("authenticated (login #%d) -> %s", self.login_count, self.instance_url)

    async def revoke(self, token: str) -> None:
        """Revoke an access token — produces a Logout ELF event for that session."""
        if not token:
            return
        with contextlib.suppress(httpx.HTTPError):
            resp = await self._client.post(
                f"{self.login_url}/services/oauth2/revoke", data={"token": token}
            )
            if resp.is_success:
                self.logout_count += 1

    def _headers(self) -> dict[str, str]:
        return {"Authorization": f"Bearer {self._token}", "Content-Type": "application/json"}

    async def _request(self, method: str, url: str, **kw) -> httpx.Response:
        headers = {**self._headers(), **kw.pop("headers", {})}
        resp = await self._client.request(method, url, headers=headers, **kw)
        if resp.status_code == 401:  # token expired mid-run — re-auth once and retry
            await self.login()
            headers = {**self._headers(), **kw.pop("headers", {})}
            resp = await self._client.request(method, url, headers=headers, **kw)
        return resp

    async def create(self, sobject: str, fields: dict, quiet: bool = False) -> str | None:
        # allowSave=true overrides Salesforce duplicate-alert rules so the
        # finite name pool never hard-fails a create as a "duplicate".
        resp = await self._request(
            "POST", f"{self._base}/sobjects/{sobject}", json=fields,
            headers={"Sforce-Duplicate-Rule-Header": "allowSave=true"},
        )
        if resp.status_code == 201:
            return resp.json()["id"]
        # quiet=True for capability-probed objects: a missing feature is expected,
        # not an error worth a warning.
        emit = log.debug if quiet else log.warning
        emit("create %s failed HTTP %d: %s", sobject, resp.status_code, resp.text[:300])
        return None

    async def update(self, sobject: str, record_id: str, fields: dict) -> bool:
        resp = await self._request(
            "PATCH", f"{self._base}/sobjects/{sobject}/{record_id}", json=fields
        )
        if resp.status_code == 204:
            return True
        log.warning("update %s/%s failed HTTP %d", sobject, record_id, resp.status_code)
        return False

    async def query(self, soql: str) -> dict:
        resp = await self._request(
            "GET", f"{self._base}/query", params={"q": soql}
        )
        resp.raise_for_status()
        return resp.json()

    async def search(self, sosl: str) -> None:
        resp = await self._request("GET", f"{self._base}/search", params={"q": sosl})
        if not resp.is_success:
            log.debug("search failed HTTP %d: %s", resp.status_code, resp.text[:200])

    async def list_reports(self) -> list[str]:
        resp = await self._request("GET", f"{self._base}/analytics/reports")
        if not resp.is_success:
            return []
        return [r["id"] for r in resp.json()]

    async def run_report(self, report_id: str) -> None:
        resp = await self._request(
            "GET", f"{self._base}/analytics/reports/{report_id}",
            params={"includeDetails": "false"},
        )
        if not resp.is_success:
            log.debug("report %s failed HTTP %d", report_id, resp.status_code)

    async def run_apex(self, body: str) -> None:
        resp = await self._request(
            "GET", f"{self._base}/tooling/executeAnonymous/",
            params={"anonymousBody": body},
        )
        if not resp.is_success:
            log.debug("apex failed HTTP %d: %s", resp.status_code, resp.text[:200])

    async def bulk_insert(self, sobject: str, csv_body: str) -> None:
        create = await self._request(
            "POST", f"{self._base}/jobs/ingest",
            json={
                "object": sobject,
                "operation": "insert",
                "lineEnding": "LF",
                "contentType": "CSV",
            },
        )
        if create.status_code != 200:
            log.debug("bulk create job failed HTTP %d: %s", create.status_code, create.text[:200])
            return
        job_id = create.json()["id"]
        put = await self._request(
            "PUT", f"{self._base}/jobs/ingest/{job_id}/batches",
            content=csv_body, headers={"Content-Type": "text/csv"},
        )
        if put.status_code not in (200, 201):
            log.debug("bulk upload failed HTTP %d", put.status_code)
            return
        await self._request(
            "PATCH", f"{self._base}/jobs/ingest/{job_id}",
            json={"state": "UploadComplete"},
        )

    async def bulk_query(self, soql: str) -> None:
        """Submit a Bulk API 2.0 query job (BulkApi ELF events, query flavour)."""
        resp = await self._request(
            "POST", f"{self._base}/jobs/query", json={"operation": "query", "query": soql}
        )
        if resp.status_code not in (200, 201):
            log.debug("bulk query failed HTTP %d: %s", resp.status_code, resp.text[:200])

    async def describe_global(self) -> None:
        resp = await self._request("GET", f"{self._base}/sobjects/")
        if not resp.is_success:
            log.debug("describe global failed HTTP %d", resp.status_code)

    async def describe_sobject(self, sobject: str) -> None:
        resp = await self._request("GET", f"{self._base}/sobjects/{sobject}/describe/")
        if not resp.is_success:
            log.debug("describe %s failed HTTP %d", sobject, resp.status_code)

    async def composite_batch(self, subrequests: list[dict]) -> None:
        """Run a batch of subrequests in one round-trip (composite API usage)."""
        resp = await self._request(
            "POST", f"{self._base}/composite/batch", json={"batchRequests": subrequests}
        )
        if not resp.is_success:
            log.debug("composite batch failed HTTP %d: %s", resp.status_code, resp.text[:200])

    async def upload_file(
        self, title: str, filename: str, body: bytes, description: str
    ) -> str | None:
        """Upload a ContentVersion (file). Produces ContentTransfer/file ELF events."""
        return await self.create(
            "ContentVersion",
            {
                "Title": title,
                "PathOnClient": filename,
                "VersionData": base64.b64encode(body).decode("ascii"),
                "Description": description,
            },
        )

    async def download_file(self, content_version_id: str) -> None:
        """Download a file's binary — produces a file-transfer ELF event."""
        resp = await self._request(
            "GET", f"{self._base}/sobjects/ContentVersion/{content_version_id}/VersionData"
        )
        if not resp.is_success:
            log.debug("file download failed HTTP %d", resp.status_code)

    async def run_report_async(self, report_id: str) -> None:
        resp = await self._request(
            "POST", f"{self._base}/analytics/reports/{report_id}/instances"
        )
        if not resp.is_success:
            log.debug("async report %s failed HTTP %d", report_id, resp.status_code)

    async def list_dashboards(self) -> list[str]:
        resp = await self._request("GET", f"{self._base}/analytics/dashboards")
        if not resp.is_success:
            return []
        payload = resp.json()
        items = payload.get("dashboards", payload) if isinstance(payload, dict) else payload
        return [d["id"] for d in items if isinstance(d, dict) and "id" in d]

    async def get_dashboard(self, dashboard_id: str) -> None:
        resp = await self._request("GET", f"{self._base}/analytics/dashboards/{dashboard_id}")
        if not resp.is_success:
            log.debug("dashboard %s failed HTTP %d", dashboard_id, resp.status_code)

    async def delete_many(self, ids: list[str]) -> int:
        """Delete up to 200 records via the sObject Collections API. Returns count deleted."""
        deleted = 0
        for i in range(0, len(ids), 200):
            chunk = ids[i : i + 200]
            resp = await self._request(
                "DELETE", f"{self._base}/composite/sobjects",
                params={"ids": ",".join(chunk), "allOrNone": "false"},
            )
            if resp.is_success:
                deleted += sum(1 for r in resp.json() if r.get("success"))
            else:
                log.warning("delete batch failed HTTP %d: %s", resp.status_code, resp.text[:200])
        return deleted


# ---------------------------------------------------------------------------
# Activity engine
# ---------------------------------------------------------------------------

# Object types that carry the Description marker, deleted in this order so
# referencing/child records go before the parents they point at (Account last).
CLEANUP_OBJECTS = [
    "Contract", "Task", "Event", "Case", "Campaign",
    "Opportunity", "Contact", "Lead", "Account",
]


class ActivityEngine:
    def __init__(self, sf: Salesforce) -> None:
        self.sf = sf
        # bounded pools of recently created ids, so updates/relationships work
        self.pools: dict[str, deque[str]] = defaultdict(lambda: deque(maxlen=200))
        self.counts: dict[str, int] = defaultdict(int)
        self._reports: list[str] = []
        self._dashboards: list[str] = []
        # optional features confirmed present in this org (see discover())
        self.caps: set[str] = set()
        # realistic value pools drawn from data/*.csv (or built-in fallback),
        # plus a few real, well-known companies for extra realism
        self.companies = load_companies() + real_companies()
        self.people = load_people()

    async def discover(self) -> None:
        """Probe optional features once so the menu only offers what works."""
        self._reports = await self.sf.list_reports()
        if self._reports:
            self.caps.add("report")
        self._dashboards = await self.sf.list_dashboards()
        if self._dashboards:
            self.caps.add("dashboard")
        if await self.act_create_campaign():
            self.caps.add("campaign")
        if await self.act_create_contract():
            self.caps.add("contract")
        log.info("capabilities: %s", ", ".join(sorted(self.caps)) or "core only")

    def _company(self) -> Company:
        return random.choice(self.companies)

    def _company_name(self) -> str:
        return _uniqueify(random.choice(self.companies).name)

    def _person(self) -> Person:
        return random.choice(self.people)

    def _remember(self, sobject: str, record_id: str | None) -> str | None:
        if record_id:
            self.pools[sobject].append(record_id)
            self.counts[f"create:{sobject}"] += 1
        return record_id

    def _pick(self, sobject: str) -> str | None:
        pool = self.pools[sobject]
        return random.choice(pool) if pool else None

    async def _ensure_account(self) -> str | None:
        return self._pick("Account") or await self.act_create_account()

    # --- create actions -------------------------------------------------

    async def act_create_account(self) -> str | None:
        city, country = random.choice(_CITIES)
        company = self._company()
        fields = {
            "Name": _uniqueify(company.name),
            "Industry": company.industry,
            "Type": random.choice(_ACCOUNT_TYPES),
            "Rating": random.choice(_RATINGS),
            "AnnualRevenue": random.randint(1, 500) * 100000,
            "NumberOfEmployees": random.randint(5, 25000),
            "Phone": _rand_phone(),
            "BillingCity": city,
            "BillingCountry": country,
            "Website": company.website,
            "Description": f"{_desc('account')} {company.description}",
        }
        return self._remember("Account", await self.sf.create("Account", fields))

    async def act_create_contact(self) -> str | None:
        account_id = await self._ensure_account()
        person = self._person()
        fields = {
            "FirstName": person.first,
            "LastName": person.last,
            "Email": _rand_email(person.first, person.last),
            "Phone": _rand_phone(),
            "Title": person.title,
            "Description": _desc("contact"),
        }
        if account_id:
            fields["AccountId"] = account_id
        return self._remember("Contact", await self.sf.create("Contact", fields))

    async def act_create_lead(self) -> str | None:
        person = self._person()
        company = self._company()
        fields = {
            "FirstName": person.first,
            "LastName": person.last,
            "Company": _uniqueify(company.name),
            "Email": _rand_email(person.first, person.last),
            "Phone": _rand_phone(),
            "Title": person.title,
            "Status": random.choice(_LEAD_STATUSES),
            "LeadSource": random.choice(_LEAD_SOURCES),
            "Industry": company.industry,
            "Description": _desc("lead"),
        }
        return self._remember("Lead", await self.sf.create("Lead", fields))

    async def act_create_opportunity(self) -> str | None:
        account_id = await self._ensure_account()
        fields = {
            "Name": f"{self._company_name()} - {random.choice(_COMPANY_QUALIFIERS)} deal",
            "StageName": random.choice(_OPP_STAGES),
            "CloseDate": _future_date(),
            "Amount": random.randint(5, 500) * 1000,
            "LeadSource": random.choice(_LEAD_SOURCES),
            "Description": _desc("opportunity"),
        }
        if account_id:
            fields["AccountId"] = account_id
        return self._remember("Opportunity", await self.sf.create("Opportunity", fields))

    async def act_create_case(self) -> str | None:
        account_id = await self._ensure_account()
        fields = {
            "Subject": random.choice(
                ["Login issue", "Billing question", "Feature request", "Integration error",
                 "Performance degradation", "Data import help", "Access request"]
            ),
            "Status": random.choice(_CASE_STATUSES),
            "Origin": random.choice(_CASE_ORIGINS),
            "Priority": random.choice(_CASE_PRIORITIES),
            "Type": random.choice(_CASE_TYPES),
            "Description": _desc("case"),
        }
        if account_id:
            fields["AccountId"] = account_id
        contact_id = self._pick("Contact")
        if contact_id:
            fields["ContactId"] = contact_id
        return self._remember("Case", await self.sf.create("Case", fields))

    async def act_create_task(self) -> str | None:
        fields = {
            "Subject": random.choice(_TASK_SUBJECTS),
            "Status": random.choice(["Not Started", "In Progress", "Completed"]),
            "Priority": random.choice(["High", "Normal", "Low"]),
            "ActivityDate": _future_date(30),
            "Description": _desc("task"),
        }
        who = self._pick("Contact")
        what = self._pick("Opportunity") or self._pick("Account")
        if who:
            fields["WhoId"] = who
        if what:
            fields["WhatId"] = what
        return self._remember("Task", await self.sf.create("Task", fields))

    async def act_create_event(self) -> str | None:
        fields = {
            "Subject": random.choice(_EVENT_SUBJECTS),
            "ActivityDateTime": _soon_datetime(),
            "DurationInMinutes": random.choice([15, 30, 45, 60]),
            "Description": _desc("event"),
        }
        who = self._pick("Contact")
        what = self._pick("Opportunity") or self._pick("Account")
        if who:
            fields["WhoId"] = who
        if what:
            fields["WhatId"] = what
        return self._remember("Event", await self.sf.create("Event", fields))

    # --- mutate actions -------------------------------------------------

    async def act_update_record(self) -> None:
        sobject = random.choice(["Account", "Contact", "Lead", "Case"])
        rid = self._pick(sobject)
        if not rid:
            return
        patches = {
            "Account": {
                "Rating": random.choice(_RATINGS),
                "NumberOfEmployees": random.randint(5, 25000),
            },
            "Contact": {"Title": random.choice(_TITLES), "Phone": _rand_phone()},
            "Lead": {"Status": random.choice(_LEAD_STATUSES)},
            "Case": {
                "Priority": random.choice(_CASE_PRIORITIES),
                "Status": random.choice(_CASE_STATUSES),
            },
        }[sobject]
        if await self.sf.update(sobject, rid, patches):
            self.counts[f"update:{sobject}"] += 1

    async def act_advance_opportunity(self) -> None:
        rid = self._pick("Opportunity")
        if not rid:
            return
        stage = random.choice(_OPP_STAGE_ADVANCE)
        if await self.sf.update("Opportunity", rid, {"StageName": stage}):
            self.counts["advance:Opportunity"] += 1

    # NOTE: deliberately no "close case" action — closing a Case fires
    # Salesforce's post-close Survey email flow, which spams the org user's
    # mailbox. Cases are created and worked/escalated but never closed here.

    # --- read / misc actions -------------------------------------------

    async def act_query(self) -> None:
        soql = random.choice(
            [
                "SELECT Id, Name, Industry FROM Account ORDER BY CreatedDate DESC LIMIT 20",
                "SELECT Id, Name, Email FROM Contact ORDER BY CreatedDate DESC LIMIT 20",
                "SELECT Id, Name, StageName, Amount FROM Opportunity "
                "WHERE IsClosed = false LIMIT 20",
                "SELECT Id, Subject, Status FROM Case WHERE Status != 'Closed' LIMIT 20",
                "SELECT Id, Company, Status FROM Lead ORDER BY CreatedDate DESC LIMIT 20",
                "SELECT COUNT() FROM Task",
            ]
        )
        with contextlib.suppress(httpx.HTTPStatusError):
            await self.sf.query(soql)
            self.counts["query"] += 1

    async def act_search(self) -> None:
        term = random.choice(
            [self._company().name.split()[0], self._person().last, self._person().first]
        )
        sosl = (
            f"FIND {{{term}}} IN ALL FIELDS RETURNING "
            "Account(Id, Name), Contact(Id, Name), Lead(Id, Name), Opportunity(Id, Name)"
        )
        await self.sf.search(sosl)
        self.counts["search"] += 1

    async def act_report(self) -> None:
        if not self._reports:
            return
        report_id = random.choice(self._reports)
        if random.random() < 0.4:
            await self.sf.run_report_async(report_id)
            self.counts["report:async"] += 1
        else:
            await self.sf.run_report(report_id)
            self.counts["report"] += 1

    async def act_dashboard(self) -> None:
        if not self._dashboards:
            return
        await self.sf.get_dashboard(random.choice(self._dashboards))
        self.counts["dashboard"] += 1

    async def act_apex(self) -> None:
        n = random.randint(1, 5)
        body = (
            "List<Account> a = [SELECT Id, Name FROM Account "
            f"ORDER BY CreatedDate DESC LIMIT {n}]; "
            f"System.debug('sf2loki synthetic apex saw ' + a.size() + ' accounts');"
        )
        await self.sf.run_apex(urllib.parse.quote(body))
        self.counts["apex"] += 1

    async def act_bulk(self) -> None:
        rows = ["FirstName,LastName,Email,Title,Description"]
        for _ in range(random.randint(5, 25)):
            person = self._person()
            rows.append(
                f"{person.first},{person.last},{_rand_email(person.first, person.last)},"
                f"{person.title},{MARKER} bulk contact"
            )
        await self.sf.bulk_insert("Contact", "\n".join(rows))
        self.counts["bulk:Contact"] += 1

    async def act_bulk_query(self) -> None:
        soql = random.choice(
            [
                "SELECT Id, Name FROM Account",
                "SELECT Id, Email FROM Contact",
                "SELECT Id, StageName, Amount FROM Opportunity",
                "SELECT Id, Company, Status FROM Lead",
            ]
        )
        await self.sf.bulk_query(soql)
        self.counts["bulkquery"] += 1

    async def act_describe(self) -> None:
        if random.random() < 0.4:
            await self.sf.describe_global()
        else:
            await self.sf.describe_sobject(
                random.choice(["Account", "Contact", "Lead", "Opportunity", "Case"])
            )
        self.counts["describe"] += 1

    async def act_composite(self) -> None:
        ver = f"v{self.sf.api_version}"
        subrequests = [
            {"method": "GET",
             "url": f"{ver}/query?q={urllib.parse.quote('SELECT Id, Name FROM Account LIMIT 5')}"},
            {"method": "GET", "url": f"{ver}/sobjects/Contact/describe"},
            {"method": "GET", "url": f"{ver}/limits"},
        ]
        await self.sf.composite_batch(subrequests)
        self.counts["composite"] += 1

    async def act_file(self) -> None:
        stamp = "".join(random.choices(string.ascii_lowercase + string.digits, k=6))
        lines = "\n".join(
            f"line {i}: {random.randint(0, 9999)}" for i in range(random.randint(3, 20))
        )
        body = (
            f"{MARKER} synthetic file {stamp}\n"
            f"Generated for observability testing.\n{lines}"
        ).encode()
        cvid = await self.sf.upload_file(
            title=f"sf2loki note {stamp}",
            filename=f"sf2loki-{stamp}.txt",
            body=body,
            description=_desc("file"),
        )
        self._remember("ContentVersion", cvid)
        if cvid:
            await self.sf.download_file(cvid)
            self.counts["file:download"] += 1

    async def act_create_campaign(self) -> str | None:
        fields = {
            "Name": f"{random.choice(_CAMPAIGN_NAMES)} {random.randint(2, 999)}",
            "Type": random.choice(_CAMPAIGN_TYPES),
            "Status": random.choice(_CAMPAIGN_STATUSES),
            "IsActive": True,
            "StartDate": _today(),
            "Description": _desc("campaign"),
        }
        cid = self._remember("Campaign", await self.sf.create("Campaign", fields, quiet=True))
        if cid and random.random() < 0.7:
            await self.act_add_campaign_member(cid)
        return cid

    async def act_add_campaign_member(self, campaign_id: str | None = None) -> None:
        cid = campaign_id or self._pick("Campaign")
        if not cid:
            return
        fields: dict = {"CampaignId": cid, "Status": "Sent"}
        contact_id = self._pick("Contact")
        if contact_id:
            fields["ContactId"] = contact_id
        else:
            lead_id = self._pick("Lead")
            if not lead_id:
                return
            fields["LeadId"] = lead_id
        # CampaignMember has no Description; it is cascade-deleted with its Campaign.
        if await self.sf.create("CampaignMember", fields, quiet=True):
            self.counts["campaignmember"] += 1

    async def act_create_contract(self) -> str | None:
        account_id = await self._ensure_account()
        if not account_id:
            return None
        fields = {
            "AccountId": account_id,
            "Status": "Draft",
            "StartDate": _today(),
            "ContractTerm": random.choice([12, 24, 36]),
            "Description": _desc("contract"),
        }
        return self._remember("Contract", await self.sf.create("Contract", fields, quiet=True))

    # --- weighted menu --------------------------------------------------

    def _menu(self) -> list[tuple]:
        # Core actions available in any org.
        menu: list[tuple] = [
            (self.act_create_account, 8),
            (self.act_create_contact, 10),
            (self.act_create_lead, 8),
            (self.act_create_opportunity, 6),
            (self.act_create_case, 6),
            (self.act_create_task, 8),
            (self.act_create_event, 5),
            (self.act_update_record, 10),
            (self.act_advance_opportunity, 4),
            (self.act_query, 12),
            (self.act_search, 8),
            (self.act_apex, 2),
            (self.act_bulk, 2),
            (self.act_bulk_query, 2),
            (self.act_describe, 3),
            (self.act_composite, 4),
            (self.act_file, 4),
        ]
        # Capability-gated actions (only offered when discover() confirmed them).
        if "report" in self.caps:
            menu.append((self.act_report, 3))
        if "dashboard" in self.caps:
            menu.append((self.act_dashboard, 2))
        if "campaign" in self.caps:
            menu.append((self.act_create_campaign, 4))
            menu.append((self.act_add_campaign_member, 3))
        if "contract" in self.caps:
            menu.append((self.act_create_contract, 3))
        return menu

    async def tick(self) -> None:
        actions, weights = zip(*self._menu(), strict=True)
        action = random.choices(actions, weights=weights, k=1)[0]
        try:
            await action()
        except Exception as exc:
            log.warning("action %s raised: %s", action.__name__, exc)

    def summary(self) -> str:
        if not self.counts:
            return "no activity yet"
        return ", ".join(f"{k}={v}" for k, v in sorted(self.counts.items()))


# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------


async def _collect_marker_ids(sf: Salesforce, sobject: str, id_field: str = "Id") -> list[str]:
    """Paginate `SELECT {id_field}, Description FROM {sobject}`, keeping marked ids."""
    ids: list[str] = []
    soql = f"SELECT {id_field}, Description FROM {sobject}"
    result = await sf.query(soql)
    ids.extend(marker_ids(result.get("records", []), id_field))
    while not result.get("done", True) and result.get("nextRecordsUrl"):
        resp = await sf._request("GET", f"{sf.instance_url}{result['nextRecordsUrl']}")
        resp.raise_for_status()
        result = resp.json()
        ids.extend(marker_ids(result.get("records", []), id_field))
    return ids


async def cleanup(sf: Salesforce) -> None:
    """Delete every record this tool ever created.

    Description is a Long Text Area, which SOQL cannot filter on (it raises
    INVALID_FIELD), so we SELECT it and match the MARKER client-side. Objects
    are visited children-first (Account last) so parents delete cleanly.
    """
    total = 0
    for sobject in CLEANUP_OBJECTS:
        try:
            ids = await _collect_marker_ids(sf, sobject)
        except httpx.HTTPStatusError as exc:
            log.warning("cleanup query %s failed: %s", sobject, exc)
            continue
        if ids:
            deleted = await sf.delete_many(ids)
            total += deleted
            log.info("deleted %d %s record(s)", deleted, sobject)

    # Files: the marker lives on ContentVersion; delete the parent ContentDocument
    # (which removes all its versions) via the de-duplicated document ids.
    try:
        doc_ids = list(dict.fromkeys(
            await _collect_marker_ids(sf, "ContentVersion", "ContentDocumentId")
        ))
    except httpx.HTTPStatusError as exc:
        log.warning("cleanup query files failed: %s", exc)
        doc_ids = []
    if doc_ids:
        deleted = await sf.delete_many(doc_ids)
        total += deleted
        log.info("deleted %d file(s)", deleted)

    log.info("cleanup complete — %d record(s) removed", total)


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------


async def run(args: argparse.Namespace) -> None:
    async with httpx.AsyncClient(timeout=30.0) as client:
        sf = Salesforce(client, args.api_version)
        await sf.login()

        if args.cleanup:
            await cleanup(sf)
            return

        engine = ActivityEngine(sf)
        await engine.discover()
        stop = asyncio.Event()

        def _handle_signal() -> None:
            log.info("shutdown requested — finishing up")
            stop.set()

        loop = asyncio.get_running_loop()
        for sig in (signal.SIGINT, signal.SIGTERM):
            with contextlib.suppress(NotImplementedError):
                loop.add_signal_handler(sig, _handle_signal)

        interval = 60.0 / max(args.ops_per_min, 1)
        deadline = (
            loop.time() + args.duration if args.duration > 0 else None
        )
        last_login = loop.time()
        ticks = 0
        log.info(
            "generating activity: ~%d ops/min (every ~%.1fs), relogin every %ds%s",
            args.ops_per_min, interval, args.relogin_every,
            f", for {args.duration}s" if args.duration else " (Ctrl-C to stop)",
        )

        while not stop.is_set():
            await engine.tick()
            ticks += 1
            if ticks % 20 == 0:
                log.info("[%d ops] %s", ticks, engine.summary())

            now = loop.time()
            if now - last_login >= args.relogin_every:
                previous = sf._token
                await sf.login()
                await sf.revoke(previous)  # Logout ELF event for the retired session
                last_login = now
            if deadline is not None and now >= deadline:
                log.info("duration reached")
                break

            # jittered pacing so the traffic pattern looks organic
            delay = random.uniform(interval * 0.4, interval * 1.6)
            with contextlib.suppress(asyncio.TimeoutError):
                await asyncio.wait_for(stop.wait(), timeout=delay)

        log.info("done after %d ops — %s", ticks, engine.summary())
        log.info("logins: %d, logouts: %d", sf.login_count, sf.logout_count)
        log.info("run with --cleanup to delete the %s-tagged records", MARKER)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "--env-file", type=Path, help="load KEY=VALUE env vars from this file (e.g. .env.dev)"
    )
    p.add_argument(
        "--ops-per-min", type=int, default=6, help="approx operations per minute (default 6)"
    )
    p.add_argument(
        "--duration", type=int, default=0, help="run for N seconds then stop (0 = until Ctrl-C)"
    )
    p.add_argument(
        "--relogin-every", type=int, default=420,
        help="re-authenticate every N seconds (Login events)",
    )
    p.add_argument(
        "--api-version", default=os.environ.get("SF_API_VERSION", "60.0"),
        help="Salesforce API version",
    )
    p.add_argument(
        "--cleanup", action="store_true", help="delete all records this tool created, then exit"
    )
    p.add_argument("--verbose", "-v", action="store_true", help="debug logging")
    return p.parse_args(argv)


def main() -> None:
    args = parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        datefmt="%H:%M:%S",
        stream=sys.stderr,
    )
    if not args.verbose:
        # httpx logs every request at INFO; keep our own summary lines readable.
        logging.getLogger("httpx").setLevel(logging.WARNING)
    if args.env_file:
        load_env_file(args.env_file)
    try:
        asyncio.run(run(args))
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
